-- Migration: Insert Mountain Groups Data
-- Purpose: Seed the pathly.mountain_groups table with data from GOT mountain groups documentation
-- Affected: pathly.mountain_groups table
-- Note: Inserts all entries from .docs/_build-support/got_mountain_groups.md, including duplicates in name and symbol as per the source data
--       Assumes the table is empty or duplicates are allowed after constraint removal

INSERT INTO pathly.mountain_groups (name, symbol) VALUES
('Tatry Wysokie', 'T.01'),
('Tatry Zachodnie', 'T.02'),
('Podtatrze', 'T.03'),
('Zapadne Tatry - (Tatry Zachodnie - Słowacja)', 'Zapadne Tatry'),
('Vysoke Tatry - (Tatry Wysokie - Słowacja)', 'Vysoke Tatry'),
('Belanske Tatry - (Tatry Bielskie - Słowacja)', 'Belanske Tatry'),
('Tatry Słowackie - szlaki z przewodnikiem', 'Tatry Słowackie'),
('Niske Tatry - (Niskie Tatry - Słowacja)', 'Niske Tatry'),
('Beskid Śląski', 'BZ.01'),
('Beskid Żywiecki', 'BZ.02'),
('Beskid Mały', 'BZ.03'),
('Beskid Średni', 'BZ.04'),
('Gorce', 'BZ.05'),
('Beskid Wyspowy', 'BZ.06'),
('Orawa', 'BZ.07'),
('Spisz i Pieniny', 'BZ.08'),
('Beskid Sądecki', 'BZ.09'),
('Pogórze Wielickie', 'BZ.10'),
('Pogórze Wiśnickie', 'BZ.11'),
('Pogórze Rożnowskie', 'BZ.12'),
('Pogórze Ciężkowickie', 'BW.01'),
('Beskid Niski część zachodnia', 'BW.02'),
('Beskid Niski część wschodnia', 'BW.02'),
('Bieszczady', 'BW.03'),
('Pogórze Strzyżowsko-Dynowskie', 'BW.04'),
('Pogórze Przemyskie', 'BW.05'),
('Góry Świętokrzyskie', 'Ł01'),
('Góry Świętokrzyskie', 'Ł02'),
('Góry Świętokrzyskie', 'Ł03'),
('Góry Świętokrzyskie', 'Ł04'),
('Góry Świętokrzyskie', 'Ł05'),
('Góry Izerskie', 'S.01'),
('Pogórze Izerskie', 'S.02'),
('Karkonosze', 'S.03'),
('Kotlina Jeleniogórska', 'S.04'),
('Rudawy Janowickie', 'S.05'),
('Góry Kaczawskie', 'S.06'),
('Pogórze Kaczawskie', 'S.07'),
('Kotlina Kamiennogórska', 'S.08'),
('Góry Kamienne', 'S.09'),
('Góry Wałbrzyskie, Pogórze Bolkowsko-Wałbrzyskie', 'S.10'),
('Góry Sowie, Wzgórza Włodzickie', 'S.11'),
('Góry Bardzkie', 'S.12'),
('Góry Stołowe, Wzgórza Lewińskie', 'S.13'),
('Góry Orlickie, Góry Bystrzyckie', 'S.14'),
('Kotlina Kłodzka, Rów Górnej Nysy', 'S.15'),
('Masyw Śnieżnika, Góry Bialskie', 'S.16'),
('Góry Złote', 'S.17'),
('Góry Opawskie', 'S.18'),
('Wzgórza Strzegomskie', 'S.19'),
('Masyw Ślęży, Równina Świdnicka, Kotlina Dzierżoniowska', 'S.20'),
('Wzgórza Niemczańsko-Strzelińskie, Przedgórze Paczkowskie', 'S.21'),
('Słowacki Raj', 'Słowacki Raj'),
('Mała Fatra - Vrátna', 'Mała Fatra - Vrátna'),
('Mała Fatra - Martinské hole', 'Mała Fatra - Martinské hole'),
('Veľká Fatra i Choć', 'Veľká Fatra i Choć'),
('Kysucke Beskydy - Grzbiet Graniczny', 'Kysucke Beskydy - Grzbiet Graniczny'),
('Oravské Beskydy - Słowacja', 'Oravské Beskydy - Słowacja'),
('Pieniny - Słowacja', 'Pieniny - Słowacja');
