-- Migration: Drop Unique Constraints on Mountain Groups
-- Purpose: Remove UNIQUE constraints on name and symbol to allow duplicate entries as per data requirements
-- Affected: pathly.mountain_groups table
-- Note: This assumes standard constraint names generated by Postgres for unique columns

-- Drop unique constraint on name
ALTER TABLE pathly.mountain_groups 
DROP CONSTRAINT IF EXISTS mountain_groups_name_key;

-- Drop unique constraint on symbol
ALTER TABLE pathly.mountain_groups 
DROP CONSTRAINT IF EXISTS mountain_groups_symbol_key;
